import { useEffect, useState } from 'react'
import { readConsent, saveConsent, startAnalytics } from './lib/analytics'

export default function PrivacyCenter() {
  const [choice, setChoice] = useState(readConsent)
  const [open, setOpen] = useState(false)
  useEffect(() => startAnalytics(), [])
  const choose = next => { saveConsent(next); setChoice(next) }
  return <>{!choice && <aside className="consent-banner" aria-label="Cookievalg"><div><strong>Vil du dele anonym besøgsstatistik?</strong><p>Praktik Tracker virker fuldt ud uden statistik. Dine timer, noter og kontooplysninger indgår aldrig.</p><button className="consent-link" onClick={() => setOpen(true)}>Læs cookie- og privatlivspolitikken</button></div><div className="consent-actions"><button className="consent-secondary" onClick={() => choose('necessary')}>Kun nødvendige</button><button className="consent-primary" onClick={() => choose('analytics')}>Tillad statistik</button></div></aside>}<button className="privacy-trigger" onClick={() => setOpen(true)}>Cookiepolitik</button>{open && <div className="privacy-backdrop" role="presentation" onMouseDown={e => e.target === e.currentTarget && setOpen(false)}><section className="privacy-dialog" role="dialog" aria-modal="true" aria-labelledby="privacy-title"><button className="privacy-close" aria-label="Luk" onClick={() => setOpen(false)}>×</button><p className="privacy-kicker">COOKIE- OG PRIVATLIVSPOLITIK · VERSION 1 · 9. SEPTEMBER 2026</p><h2 id="privacy-title">Dit praktikforløb er dit.</h2><p>Praktik Tracker drives af Zoubir Benslimane, som er dataansvarlig. Kontakt: <a href="mailto:zoubben@gmail.com">zoubben@gmail.com</a>.</p><h3>Lokal lagring og statistik</h3><div className="privacy-table"><div><strong>Login — nødvendigt</strong><span>Supabases lokale sessionsnøgle holder dig logget ind.</span><span>Til du logger ud eller rydder browserdata.</span></div><div><strong>Samtykke — nødvendigt</strong><span><code>zb_consent_v1</code> husker dit valg.</span><span>Op til 12 måneder.</span></div><div><strong>Statistik — valgfrit</strong><span>Tilfældig sessionskode, side, tidspunkt, henvisende domæne, enhedstype og sprog.</span><span>Slettes løbende efter 180 dage.</span></div></div><p>Besøgsstatistik indeholder ikke fulde IP-adresser, timer, noter, praktiksted, e-mail eller søgeparametre. Dine egne praktikdata bruges alene til at levere trackeren.</p><h3>Behandling og rettigheder</h3><p>Valgfri statistik bygger på samtykke. Konto- og praktikdata behandles for at levere tjenesten. Cloudflare leverer hosting og sikkerhed, og Supabase leverer login og database i EU-regionen. Leverandørernes tekniske driftslogs følger deres egne sikkerheds- og opbevaringsvilkår.</p><p>Du kan bede om indsigt, rettelse eller sletning på mail og klage til Datatilsynet.</p><div className="privacy-choice"><span>Nuværende valg: <strong>{choice === 'analytics' ? 'Statistik tilladt' : choice === 'necessary' ? 'Kun nødvendige' : 'Intet valg endnu'}</strong></span><button className="consent-secondary" onClick={() => choose('necessary')}>Afvis statistik</button><button className="consent-primary" onClick={() => choose('analytics')}>Tillad statistik</button></div></section></div>}</>
}
